services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: temperature_db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"  

  # frontend:
  #  build:
  #    context: ./frontend
  #  command: npm start
  #  volumes:
  #    - ./frontend:/app
  #    - /app/node_modules
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - backend